### ISSUE TITLE
WorldWindow macOS gazetteer errors with valid coordinate input

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/WorldWindJava#41]
Issue #40 describes an issue with using placenames, but valid coordinates on macOS also display message "No search string specified"

**Comment by pdavidc** [comment]
Fixed by #40

**Comment by zglueck** [comment]
Searching by place names does work with the fix from #40, but the coordinate input still does not work. The tool tip displays "Any of these: 45.5 -120.2 or 45 30 0 n 120 12 0 w or Seattle", but providing "45.5 -120.2" does not move the globe.

**Comment by zglueck** [comment]
The GazetteerPanel in the WorldWindow application doesn't include all of the functionality as the GazetteerPanel in the examples package. Notably, the parsing of coordinates isn't included.
